"""End-to-end regression against a fixture generated by the pipeline itself.

`sample.json` is the payload the demo page ships; `fixture_sample.json` is what the
ReboundingPrediction session got when it ran that payload through
`rebounding.serve` against the exact bundles now in `../models/`. Together they pin
the whole path -- canvas->model conversion, canonical slot ordering, grouped softmax,
and the conversion back -- against the pipeline rather than against this app's own
output, so a silent contract change upstream fails here instead of shipping.

Two different tolerances, for two different reasons:

* **`probability` is asserted exactly** (to the six decimals the fixture carries).
  LightGBM inference is deterministic, so any movement at all is a real change.
* **`newx`/`newy` go through the torch RNG**, so they are asserted loosely and pinned
  to `torch==2.13.0+cpu`. A torch bump should read as "the sampler moved", not as a
  mystery failure, so the check is skipped outright on a different torch rather than
  failing red.

`meanx`/`meany` is the conditional-mean scene: a stable, non-RNG anchor. It is a good
regression target and is asserted here -- but it is deliberately never drawn. Meaning
the samples together puts a player at the midpoint of two futures he never takes,
which is the drift the retrained movement model exists to remove.
"""

import json
from pathlib import Path

import pytest

HERE = Path(__file__).resolve().parent
SAMPLE = HERE.parent / "sample.json"
FIXTURE = HERE / "fixture_sample.json"

PINNED_TORCH = "2.13.0+cpu"


@pytest.fixture(scope="module")
def fixture() -> dict:
    return json.loads(FIXTURE.read_text())


@pytest.fixture(scope="module")
def bench() -> list[dict]:
    return json.loads(SAMPLE.read_text())["bench"]


@pytest.fixture(scope="module")
def served(model_path, movement_path, bench):
    """The app with movement ON -- the fixture covers newx/newy, which needs it."""
    from app import create_app
    from config import Config

    application = create_app(
        Config(
            model_path=model_path,
            movement_model_path=movement_path,
            movement_enabled=True,
            # The fixture is scene 0 of seed 0. Serving leaves this None so each
            # request draws a fresh future; see Movement.scenes.
            movement_seed=0,
        )
    )
    application.config.update(TESTING=True)
    response = application.test_client().post("/predict", json={"bench": bench})
    assert response.status_code == 200, response.get_data(as_text=True)
    return response.get_json()


def test_probabilities_match_the_pipeline_exactly(served, fixture):
    """Deterministic under LightGBM, so any drift here is a real contract change."""
    got = [round(entry["probability"], 6) for entry in served]
    assert got == fixture["probability"]


def test_probabilities_are_already_normalised(served):
    """Grouped softmax over the ten players -- the app must not re-normalise."""
    assert sum(entry["probability"] for entry in served) == pytest.approx(1.0, abs=1e-9)


def test_the_predicted_rebounder_and_full_ranking_are_unchanged(served, fixture):
    order = sorted(range(len(served)), key=lambda i: -served[i]["probability"])
    assert order == fixture["ranked"]
    assert order[0] == 3


def test_player_order_is_the_order_the_bench_was_sent_in(served, bench):
    """serve.predict re-sorts into canonical slots internally and must restore ours.

    This is the failure mode most likely to be silent: every dot still gets a
    plausible probability, just the wrong player's. The fixture's exact-match test
    would catch it too, but this states the reason.
    """
    assert len(served) == len(bench) == 10


@pytest.mark.skipif(
    __import__("torch").__version__ != PINNED_TORCH,
    reason=f"sampled scenes are pinned to torch=={PINNED_TORCH}",
)
def test_sampled_positions_match_the_fixture_scene(served, fixture):
    """Scene 0 of animate(n=12, seed=0). Loose: this went through the torch RNG."""
    for i, entry in enumerate(served):
        assert entry["newx"] == pytest.approx(fixture["newx"][i], abs=0.01)
        assert entry["newy"] == pytest.approx(fixture["newy"][i], abs=0.01)


def test_every_scene_comes_back_for_a_front_end_that_wants_the_spread(served):
    for entry in served:
        assert len(entry["scenes"]) == 12
        assert all(len(point) == 2 for point in entry["scenes"])


def test_newx_newy_is_a_draw_not_the_average_of_the_draws(served, fixture):
    """Guards the specific regression of meaning the samples before drawing them.

    If someone 'simplifies' the view by averaging scenes, newx/newy would land on
    meanx/meany. The fixture carries both, so the two are distinguishable.
    """
    drawn = [entry["newx"] for entry in served]
    assert drawn != pytest.approx(fixture["meanx"], abs=0.01)
